<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LAPTOP-QTKNQFTM" failures="1" tests="3" name="Test" time="23.033" errors="0" timestamp="2024-06-26T18:55:27 IST">
  <testcase classname="testcases.LoignTestCases" name="validLoginTest" time="1.531"/>
  <testcase classname="testcases.RegisterTestCases" name="verifyRegisterationWithInBlankData" time="3.418"/>
  <testcase classname="testcases.RegisterTestCases" name="verifyRegisterationWithValidData" time="3.83">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [https://naveenautomationlabs.com/opencart/index.php?route=account/success] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/register]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [https://naveenautomationlabs.com/opencart/index.php?route=account/success] but found [https://naveenautomationlabs.com/opencart/index.php?route=account/register]
at com.Resources.commonMethods.handleAssertions(commonMethods.java:18)
at testcases.RegisterTestCases.verifyRegisterationWithValidData(RegisterTestCases.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 29 stack frames]]>
    </failure>
  </testcase> <!-- verifyRegisterationWithValidData -->
</testsuite> <!-- Test -->
